plugins {
    id 'java-library'
    id 'maven-publish'
    id 'org.jreleaser' version '1.25.0'
    id 'de.infolektuell.jextract' version '1.4.0'
}

group = 'io.github.notstirred'
version = '0.1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

def nativesBuildDir = layout.buildDirectory.dir("nativesBuild")

def providedNatives = providers.gradleProperty("providedNatives")

tasks.register("cleanNatives", Delete) {
    group = "build"
    delete nativesBuildDir
}
tasks.named("clean") {
    dependsOn(tasks.named("cleanNatives"))
}

tasks.register("configureNatives", Exec) {
    if (SystemInfo.OS == SystemInfo.OperatingSystem.UNKNOWN || SystemInfo.ARCH == SystemInfo.Architecture.UNKNOWN) {
        throw new RuntimeException(String.format(
                "Unknown hardware, OS: %s -> %s | Arch: %s -> %s",
                System.getProperty("os.name", "?"),
                SystemInfo.OS,
                System.getProperty("os.arch", "?"),
                SystemInfo.ARCH
        ));
    }

    var buildType = providers.gradleProperty("buildType")
    inputs.property("buildType", buildType)
    // Using FetchContent so the entire input is captured within CMakeLists
    inputs.file(layout.projectDirectory.file("CMakeLists.txt"))
    outputs.dir(nativesBuildDir)

    var type = buildType.getOrElse("Debug")
    commandLine "cmake", "-DCMAKE_BUILD_TYPE=$type", "-S", "$projectDir", "-B", nativesBuildDir.get().asFile
}
tasks.register("buildNatives", Exec) {
    group = "build"
    dependsOn(tasks.named("configureNatives"))
    var buildType = providers.gradleProperty("buildType")
    inputs.property("buildType", buildType)
    // Using FetchContent so the entire input is captured within CMakeLists
    inputs.file(layout.projectDirectory.file("CMakeLists.txt"))
    inputs.dir(layout.projectDirectory.dir("native"))

    def libraryName = SystemInfo.OS.getLibraryName("leveldb_ffi")
    outputs.file(layout.buildDirectory.file("nativesBuild/Debug/${libraryName}")) // windows specific
    outputs.file(layout.buildDirectory.file("nativesBuild/Release/${libraryName}")) // windows specific
    outputs.file(layout.buildDirectory.file("nativesBuild/${libraryName}"))

    commandLine "cmake", "--build", nativesBuildDir.get().asFile
}

def copyNativesTask = tasks.register("copyNatives", Copy) {
    from tasks.named("buildNatives")
    into temporaryDir.toPath().resolve("io/github/notstirred/leveldb_ffi/natives/${SystemInfo.OS.osName}/${SystemInfo.ARCH.archName}/")
}

// Places binaries in a known directory structure so that CI can rely on it.
tasks.register("buildNativesForCI", Copy) {
    from tasks.named("buildNatives")
    into layout.buildDirectory.dir("nativeBuildForCI/${SystemInfo.OS.osName}/${SystemInfo.ARCH.archName}/")
}

def copyProvidedNativesTask = tasks.register("copyProvidedNatives", Copy) {
    inputs.property("providedNatives", providedNatives)

    var natives = providedNatives.getOrElse("")
    if (!natives.isEmpty()) {
        from file(natives)
        into temporaryDir.toPath().resolve("io/github/notstirred/leveldb_ffi/natives/")
    }
}

jextract.libraries {
    def levelDBBindings = register('levelDB') {
        includes.add(layout.projectDirectory.dir("native/include"))
        header = layout.projectDirectory.file("native/include/leveldb_ffi/c.h")
        headerClassName = "c_h"
        targetPackage = "io.github.notstirred.leveldb_ffi.ffi"
    }
    sourceSets.main {
        jextract.libraries.addLater(levelDBBindings)
    }
}

sourceSets {
    main {
        resources {
            if (providedNatives.getOrElse("").isEmpty()) { // build one for this platform
                srcDir(copyNativesTask.map { it.temporaryDir })
            } else { // use the provided binaries
                srcDir(copyProvidedNativesTask.map { it.temporaryDir })
            }
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(22)
    }

    withJavadocJar()
    withSourcesJar()
}

tasks.named("sourcesJar", Jar) {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    exclude("io/github/notstirred/leveldb_ffi/natives")
    // resources are included in sources by default, we don't want that for our natives.
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.3")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

test {
    useJUnitPlatform()
}

publishing {
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/NotStirred/leveldb-ffi")
            credentials {
                username = project.findProperty("gpr.user") ?: System.getenv("USERNAME")
                password = project.findProperty("gpr.key") ?: System.getenv("TOKEN")
            }
        }
        maven {
            name = "MavenCentralSnapshot"
            url = "https://central.sonatype.com/repository/maven-snapshots/"
            credentials {
                username = System.getenv("SONATYPE_USERNAME")
                password = System.getenv("SONATYPE_TOKEN")
            }
        }
        maven {
            name = "Staging"
            url = layout.buildDirectory.dir('staging-deploy')
        }
    }
    publications {
        LevelDBFFI(MavenPublication) {
            groupId = group
            artifactId = rootProject.name
            version = version

            artifact jar
            artifact sourcesJar
            artifact javadocJar

            pom {
                name = 'leveldb-ffi'
                description = 'A Java wrapper for leveldb with zlib-raw'
                url = 'https://github.com/NotStirred/leveldb-ffi'
                inceptionYear = '2026'
                licenses {
                    license {
                        name = 'Apache-2.0'
                        url = 'https://spdx.org/licenses/Apache-2.0.html'
                    }
                }
                developers {
                    developer {
                        id = 'NotStirred'
                        name = 'Tom Martin'
                    }
                }
                scm {
                    connection = 'scm:git:https://github.com/NotStirred/leveldb-ffi.git'
                    developerConnection = 'scm:git:ssh://github.com/NotStirred/leveldb-ffi.git'
                    url = 'http://github.com/NotStirred/leveldb-ffi'
                }
            }
        }
    }
}

jreleaser {
    signing {
        pgp {
            active = 'ALWAYS'
            armored = true
        }
    }
    deploy {
        maven {
            mavenCentral {
                'release-deploy' {
                    active = 'RELEASE'
                    url = 'https://central.sonatype.com/api/v1/publisher'
                    stagingRepository('build/staging-deploy')
                }
            }
        }
    }
}

// Keep in sync with SystemInfo in the project
public class SystemInfo {
    public static final Architecture ARCH;
    public static final OperatingSystem OS;

    static {
        String arch = System.getProperty("os.arch", "").toLowerCase().replaceAll("[^a-z0-9]+", "");
        switch (arch) {
            case "x64":
            case "x86_64":
            case "x8664":
            case "amd64":
            case "em64t":
            case "universal":
                ARCH = Architecture.x86_64;
                break;
            case "x86":
            case "x86_32":
            case "x8632":
            case "x32":
            case "i386":
            case "i486":
            case "i586":
            case "i686":
            case "pentium":
                ARCH = Architecture.x86;
                break;
            case "arm":
            case "arm32":
                ARCH = Architecture.ARM;
                break;
            case "aarch64":
                ARCH = Architecture.AARCH64;
                break;
            default:
                ARCH = Architecture.UNKNOWN;
        }

        String osName = System.getProperty("os.name", "").toLowerCase();
        if (osName.contains("linux")) {
            OS = OperatingSystem.Linux;
        } else if (osName.contains("freebsd")) {
            OS = OperatingSystem.FreeBSD;
        } else if (osName.contains("openbsd")) {
            OS = OperatingSystem.OpenBSD;
        } else if (osName.contains("netbsd")) {
            OS = OperatingSystem.NetBSD;
        } else if (osName.contains("windows")) {
            OS = OperatingSystem.Windows;
        } else if (osName.contains("mac os")) {
            OS = OperatingSystem.MAC;
        } else {
            OS = OperatingSystem.UNKNOWN;
        }
    }

    public enum OperatingSystem {
        Linux("linux", "lib", ".so"),
        FreeBSD("freebsd", "lib", ".so"),
        OpenBSD("openbsd", "lib", ".so"),
        NetBSD("netbsd", "lib", ".so"),
        Windows("windows", "", ".dll"),
        MAC("mac", "lib", ".dylib"),
        UNKNOWN("UNKNOWN", "", "");

        public final String osName;
        public final String libPrefix;
        public final String libSuffix;

        OperatingSystem(String name, String libPrefix, String libSuffix) {
            this.osName = name;
            this.libPrefix = libPrefix;
            this.libSuffix = libSuffix;
        }

        public String getLibraryName(String name) {
            return this.libPrefix + name + this.libSuffix;
        }
    }

    public enum Architecture {
        x86("x86"),
        x86_64("x86_64"),
        ARM("arm"),
        AARCH64("aarch64"),
        UNKNOWN("UNKNOWN");

        public final String archName;

        Architecture(String name) {
            this.archName = name;
        }
    }
}
